K8s_Cluster:
  vars:
    install_rke2_version: v1.30.4+rke2r1
    kube_api_server: "myrke2cluster.example.tld" # Define kube-api-server URL
    token: "" # The token to join a cluster. (Only required when this inventory don't contains the initial control plane)
    ansible_user: ansible # The Ansible user on the remote machines
    # kube_api_ip: 10.0.54.107 # Will be the LB IP or the IP of the first CP within the cluster. Doesn't need to be set if this Inventory contains the first CP identified via `first_node: True`
    kubelet_resolv_conf_enabled: False # True|False
  children:
    K8s_ControlPlanes:
      hosts:
        control-plane01:
          ansible_host: 192.168.1.50 # Change to your CP-IP
          # node_name: # Change to your node-name (Optional)
          first_node: True # True|False # Just the first Control-Plane, which will provide the token.
        control-plane02:
          ansible_host: 192.168.1.51 # Change to your CP-IP
          # node_name: # Change to your node-name (Optional)
        control-plane03:
          ansible_host: 192.168.1.52 # Change to your CP-IP
          # node_name: # Change to your node-name (Optional)

    K8s_Worker:
      hosts:
        agent01:
          ansible_host: 192.168.1.54 # Change to your worker-IP
          # node_name: # Change to your node-name (Optional)
          # node_labels:
        agent02:
          ansible_host: 192.168.1.55 # Change to your worker-IP
          # node_name: # Change to your node-name (Optional)
          # node_labels:
        agent03:
          ansible_host: 192.168.1.56 # Change to your worker-IP
          # ansible_user: ansible # Change to your ansible-user
          # node_name: # Change to your node-name (Optional)
          # node_labels:
