# See https://docs.rke2.io/helm/
# In this directory "manifest" you can add every kubernetes .yaml file that you will add to your rke2 cluster.
# "kubectl apply" every file on this directory

# See https://docs.rke2.io/install/network_options/#canal-options
# You can also override pre-install helm chart like canal, nginx-ingress, etc.

# Example from https://docs.rke2.io/helm/#using-the-helm-crd

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  targetNamespace: longhorn-system
  createNamespace: true
  version: 1.6.2 # edit Longhorn-Version 
  repo: https://charts.longhorn.io
  chart: longhorn  
  valuesContent: |-
    defaultSettings:
      defaultReplicaCount: 2
