---
namespace: luceast
description: Deploy a production ready Kubernetes cluster
name: sprinkle
version: 2.27.0
readme: README.md
authors:
  - LucEast
tags:
  - infrastructure
  - kubernets
  - rke2
repository: https://github.com/LucEast/Sprinkle
issues: https://github.com/LucEast/Sprinkle/issues
documentation: https://github.com/LucEast/Sprinkle
license_file: LICENSE
dependencies:
  ansible.utils: '>=2.5.0'
  community.general: '>=3.0.0'
  ansible.netcommon: '>=5.3.0'
  ansible.posix: '>=1.5.4'
  community.docker: '>=3.11.0'
  kubernetes.core: '>=2.4.2'
manifest:
  directives:
    - recursive-exclude tests **