---
# tasks file for rke2_agent

- name: RKE2 agent and server tasks
  vars:
    rke2_common_caller_role_name: agent
  ansible.builtin.include_role:
    name: rke2_common
    tasks_from: main

- name: Does config file already have server token? # noqa command-instead-of-shell
  ansible.builtin.command: 'grep -i "^token:" /etc/rancher/rke2/config.yaml'
  register: server_token_check
  failed_when: server_token_check.rc >= 2
  changed_when: false

- name: Debug token
  ansible.builtin.debug:
    var: server_token_check

- name: Add token to config.yaml
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ rke2_token }}"
    state: present
    insertbefore: BOF
  vars:
    rke2_token: "{{ hostvars[groups['K8s_ControlPlanes'][0]].token if 'K8s_ControlPlanes' in groups and hostvars[groups['K8s_ControlPlanes'][0]].first_node | default(false) else token }}"
  when:
    - '"token:" not in server_token_check.stdout'

- name: Does config file already have server url? # noqa command-instead-of-shell
  ansible.builtin.command: 'grep -i "^server:" /etc/rancher/rke2/config.yaml'
  register: server_url_check
  failed_when: server_url_check.rc >= 2
  changed_when: false

- name: Add server url to config file
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ kubernetes_api_server_host }}:9345"
    state: present
    insertbefore: BOF
  when:
    - '"server:" not in server_url_check.stdout'

- name: Start rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent.service
    state: started
    enabled: yes
    daemon_reload: yes
