---
- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes

- name: Add resolv.conf config file
  vars:
    file_contents: "{{ lookup('file', resolv_conf_file_path) }}"
  template:
  ansible.builtin.copy:
    src: templates/ansible_header.j2
    dest: /etc/rancher/rke2/resolv.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  when:
    - resolv_conf_file_path is defined
    - resolv_conf_file_path | length > 0
  notify: Restart rke2-server

- name: Remove resolv.conf config file
  when:
    - resolv_conf_file_path is not defined or resolv_conf_file_path|length == 0
  block:
    - name: Check that the resolv.conf config file exists
      ansible.builtin.stat:
        path: "/etc/rancher/rke2/resolv.conf"
      register: stat_result

    - name: "Check that the resolv.conf config file has ansible managed comments"
      ansible.builtin.lineinfile:
        name: "/etc/rancher/rke2/resolv.conf"
        line: "## This is an Ansible managed file, contents will be overwritten ##"
        state: present
      check_mode: yes
      register: ansible_managed_check
      when: stat_result.stat.exists | bool is true

    - name: Remove the resolv.conf config file if exists and has ansible managed comments
      ansible.builtin.file:
        path: "/etc/rancher/rke2/resolv.conf"
        state: absent
      when:
        - ansible_managed_check.changed | bool is false
