---
- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0750"

- name: Does the /etc/rancher/rke2/config.yaml file exist?
  ansible.builtin.stat:
    path: /etc/rancher/rke2/config.yaml
  register: previous_rke2_config

- name: Read previous_rke2_config
  ansible.builtin.slurp:
    src: /etc/rancher/rke2/config.yaml
  register: full_orig_rke2_config
  when: previous_rke2_config.stat.exists

- name: Decode contents of slurp
  ansible.builtin.set_fact:
    orig_rke2_config: "{{ full_orig_rke2_config['content'] | b64decode }}"
  when: previous_rke2_config.stat.exists

- name: Create the /etc/rancher/rke2/config.yaml file
  ansible.builtin.file:
    path: /etc/rancher/rke2/config.yaml
    state: touch
    mode: "0640"
    owner: root
    group: root
  when: not previous_rke2_config.stat.exists

# https://github.com/ansible-collections/ansible.utils/issues/135
- name: Ensure Ansible renders any templated variables in rke2_config
  ansible.builtin.set_fact:
    rke2_config: "{{ rke2_config | default({}) }}"

# cluster-cidr
- name: Get rke2_config cluster-cidr
  ansible.builtin.set_fact:
    rke2_config_cluster_cidr: "{{ rke2_config['cluster-cidr'] | default('') }}"

# --node-label value                     (agent/node) Registering and starting kubelet with set of labels
- name: Get global_rke2_config node-labels
  ansible.builtin.set_fact:
    global_rke2_config_node_labels: "{{ global_rke2_config['node-label'] | default([]) }}"

- name: Debug global_rke2_config node-labels
  debug:
    var: global_rke2_config['node-label']

- name: Get rke2_config node-labels
  ansible.builtin.set_fact:
    rke2_config_node_labels: "{{ rke2_config['node-label'] | default([]) }}"

- name: Debug rke2_config node-labels
  debug:
    var: rke2_config['node-label']

- name: Get host var node-labels
  ansible.builtin.set_fact:
    host_var_node_labels: "{{ node_labels | default([]) }}"

- name: Debug host var node-labels
  debug:
    var: node_labels

- name: Combine rke2_config node labels and hostvar node labels
  ansible.builtin.set_fact:
    all_node_labels: "{{ global_rke2_config_node_labels + rke2_config_node_labels + host_var_node_labels }}"
  changed_when: false

- name: Add node labels to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-label"]
        value: "{{ all_node_labels }}"
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  changed_when: false

- name: Debug rke2_config["node-label"]
  debug:
    var: rke2_config["node-label"]

# --node-taint value                     (agent/node) Registering kubelet with set of taints
- name: Get global_rke2_config node-taints
  ansible.builtin.set_fact:
    global_rke2_config_node_taints: "{{ global_rke2_config['node-taint'] | default([]) }}"

- name: Get rke2_config node-taints
  ansible.builtin.set_fact:
    rke2_config_node_taints: "{{ rke2_config['node-taint'] | default([]) }}"

- name: Get host var node-taints
  ansible.builtin.set_fact:
    host_var_node_taints: "{{ node_taints | default([]) }}"

- name: Combine rke2_config node taints and hostvar node taints
  ansible.builtin.set_fact:
    all_node_taints: "{{ global_rke2_config_node_taints + rke2_config_node_taints + host_var_node_taints }}"
  changed_when: false

- name: Debug all_node_taints
  debug:
    var: all_node_taints

- name: Add node labels to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-taint"]
        value: "{{ all_node_taints }}"
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  changed_when: false

- name: Debug rke2_config node-taint
  debug:
    var: rke2_config["node-taint"]

# --node-ip value, -i value (agent/networking) IPv4/IPv6 addresses to advertise for node
- name: Add node-ip to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-ip"]
        value: "{{ node_ip }}"
  when: (node_ip is defined) and (node_ip|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (node_ip is defined) and (node_ip|length > 0)
  changed_when: false

# --node-name value (agent/node) Node name [$RKE2_NODE_NAME]
- name: Add node-name to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-name"]
        value: "{{ node_name }}"
  when: (node_name is defined) and (node_name|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (node_name is defined) and (node_name|length > 0)
  changed_when: false

# --bind-address value (listener) rke2 bind address (default: 0.0.0.0)
- name: Add bind-address to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["bind-address"]
        value: "{{ bind_address }}"
  when: (bind_address is defined) and (bind_address|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (bind_address is defined) and (bind_address|length > 0)
  changed_when: false

# --advertise-address value (listener) IPv4 address that apiserver uses
# to advertise to members of the cluster (default: node-external-ip/node-ip)
- name: Add advertise-address to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["advertise-address"]
        value: "{{ advertise_address }}"
  when: (advertise_address is defined) and (advertise_address|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (advertise_address is defined) and (advertise_address|length > 0)
  changed_when: false

# --node-external-ip value (agent/networking) IPv4/IPv6 external IP addresses to advertise for node
- name: Add node-external-ip to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-external-ip"]
        value: "{{ node_external_ip }}"
  when: (node_external_ip is defined) and (node_external_ip|length > 0)
  register: updated_rke2_config
  changed_when: false

- name: Update rke2_config to take value of updated_rke2_config # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (node_external_ip is defined) and (node_external_ip|length > 0)
  changed_when: false

# --cloud-provider-name value (agent/node) Cloud provider name
- name: Add cloud-provider-name to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["cloud-provider-name"]
        value: "{{ cloud_provider_name }}"
  when: (cloud_provider_name is defined) and (cloud_provider_name|length > 0)
  register: updated_rke2_config

- name: Update rke2_config to take value of updated_rke2_config # noqa no-handler
  ansible.builtin.set_fact:
    rke2_config: "{{ updated_rke2_config.rke2_config }}"
  when: (cloud_provider_name is defined) and (cloud_provider_name|length > 0)

- name: Get original token
  ansible.builtin.set_fact:
    original_token: "{{ orig_rke2_config | regex_search('token: (.+)') }}"
  when: previous_rke2_config.stat.exists
  changed_when: false

- name: Get original server
  ansible.builtin.set_fact:
    original_server: "{{ orig_rke2_config | regex_search('server: https://(.*):9345') }}"
  when: previous_rke2_config.stat.exists
  changed_when: false

- name: Copy resolv.conf to /etc/rancher/rke2/resolv.conf if kubelet_resolv_conf_enabled is true
  ansible.builtin.template:
    src: templates/resolv.conf.j2
    dest: /etc/rancher/rke2/resolv.conf
    owner: root
    group: root
    mode: "0644"
  when: kubelet_resolv_conf_enabled | bool

# - name: Show all hostvars for the first CP
#   debug:
#     var: hostvars[groups['K8s_ControlPlanes'][0]] if 'K8s_ControlPlanes' in groups

- name: Generate RKE2 configuration from template
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: /tmp/rendered_config.yaml
    owner: root
    group: root
    mode: "0640"

- name: Get the stat of the rendered template
  ansible.builtin.stat:
    path: /tmp/rendered_config.yaml
  register: rendered_config
  when: not ansible_check_mode

- name: Get the checksum of the rendered template
  ansible.builtin.set_fact:
    rendered_config_sha1: "{{ rendered_config.stat.checksum }}"
  changed_when: false
  when: not ansible_check_mode

- name: Overwrite /etc/rancher/rke2/config.yaml if necessary
  ansible.builtin.copy:
    src: /tmp/rendered_config.yaml
    remote_src: true
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
    backup: true
  when:
    - not ansible_check_mode
    - not previous_rke2_config.stat.exists or rendered_config_sha1 != previous_rke2_config.stat.checksum

- name: Restart rke2-server if package installed and config changed or RKE2 version changed
  ansible.builtin.service:
    state: restarted
    name: rke2-server
  when:
    - ansible_facts.services["rke2-server.service"] is defined
    - "ansible_facts.services['rke2-server.service'].state == 'running'"
    - (rendered_config_sha1 != previous_rke2_config.stat.checksum or (rke2_version_changed | default(false)))
    - not ansible_check_mode

- name: Restart rke2-agent if package installed and config changed or RKE2 version changed
  ansible.builtin.service:
    state: restarted
    name: rke2-agent
  when:
    - ansible_facts.services["rke2-agent.service"] is defined
    - "ansible_facts.services['rke2-agent.service'].state == 'running'"
    - (rendered_config_sha1 != previous_rke2_config.stat.checksum or (rke2_version_changed | default(false)))
    - not ansible_check_mode
