---
- name: Server play
  hosts: K8s_ControlPlanes
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_server
  serial: 1

- name: Agent play
  hosts: K8s_Worker
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_agent
  serial: 3

- name: Cluster manifest play
  hosts: K8s_ControlPlanes
  any_errors_fatal: true
  become: true
  roles:
    - role: cluster_manifest
